# See the writing guide of rbs: https://github.com/ruby/rbs#guides
#
module Icarus
  module Mod
    class Github
      attr_reader :client: Octokit::Client
      attr_accessor :repo: String

      def initialize: (void) -> void
      def all_files: (String) -> Array[String]

      VERSION: String
    end
  end
end
